version: "3.9"  

services:
  marauderapi:
    build: .
    # platform: linux/amd64
    container_name: marauderapi
  maraudersserver:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: maraudersserver
    ports:
      - 1433:1433 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=D&senrascanco0608
    volumes:
      - /var/lib/docker/volumes/mssql_db/_data:/var/opt/data