version: "3.9"  # optional since v1.27.0
services:
  web_api:
    build: . # build the Docker image 
    container_name: marauder_application
    ports:
      - "8080:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: marauder_server
    ports: # not actually needed, because the two services are on the same network.
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=D&senrascanco0608
